/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_MyJni */

#ifndef _Included_jni_MyJni
#define _Included_jni_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_MyJni
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_MyJni_getStringFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
